### ISSUE TITLE
Upgrade to phpoffice/phpexcel

### ISSUE THREAD

**Issue by anroots** [DracoBlue/Craur#25]
Composer reports that [codeplex/phpexcel](https://packagist.org/packages/codeplex/phpexcel) is abandoned. Please upgrade to phpoffice/phpexcel.

**Comment by shrink0r** [comment]
Check. Would like to get rid of this warning when setting up Craur:
Package codeplex/phpexcel is abandoned, you should avoid using it. Use https://packagist.org/packages/phpoffice/phpexcel instead.

**Comment by DracoBlue** [comment]
Will do in next days, busy right now :(

Am Dienstag, 17. März 2015 schrieb Thorsten Schmitt-Rink :

> Check. Would like to get rid of this warning when setting up Craur:
> Package codeplex/phpexcel is abandoned, you should avoid using it. Use
> https://packagist.org/packages/phpoffice/phpexcel instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DracoBlue/Craur/issues/25#issuecomment-82291336>.
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
I had to downgrade to in d997a4fcd13af6a83ea9a693e40ee1904d15ca51 to `phpexcel 1.7.x` to avoid failing tests
