### ISSUE TITLE
tostring throws an exception on empty xml-tag 

### ISSUE THREAD

**Issue by Christian-Krupa** [DracoBlue/Craur#26]
am empty xml-tag for example:
```
<neu neu="true" neuType="Erstausstrahlung"/>
```

throws an exception when it is converted to a string:
```
[23-Mar-2015 10:44:26 Europe/Berlin] PHP Fatal error:  Method Craur::__toString() must not throw an exception in .../class.php on line 0
```

the error messages is very hard to debug. maybe it is a better solution to display the given xml-attributes.

**Comment by Christian-Krupa** [comment]
btw. i am unable to catch the exception with in the __tostring function.

sample code:
```
christians-MacBook-Pro:test christiankrupa$ cat test.php
<?php
class foo {
	public function __tostring()
	{
		throw new exception('test');
	}	
}
try
{
	$fooo = new foo();
	echo (string)$fooo;
}
catch(exception $e)
{
	echo "catched";
}
```

execution:
```
christians-MacBook-Pro:test christiankrupa$ php test.php
PHP Fatal error:  Method foo::__toString() must not throw an exception in /Users/christiankrupa/test/test.php on line 0

Fatal error: Method foo::__toString() must not throw an exception in /Users/christiankrupa/test/test.php on line 0
```

PHP-Version:
```
christians-MacBook-Pro:test christiankrupa$ php -v
PHP 5.5.21 (cli) (built: Jan 24 2015 19:27:09) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by DracoBlue** [comment]
Can you provide a testcase when this happens in craur?

Am Montag, 23. März 2015 schrieb Christian-Krupa :

> btw. i am unable to catch the exception with in the __tostring function.
>
> sample code:
>
> christians-MacBook-Pro:test christiankrupa$ cat test.php
> <?php
> class foo {
>     public function __tostring()
>     {
>         throw new exception('test');
>     }
> }
> try
> {
>     $fooo = new foo();
>     echo (string)$fooo;
> }
> catch(exception $e)
> {
>     echo "catched";
> }
>
> execution:
>
> christians-MacBook-Pro:test christiankrupa$ php test.php
> PHP Fatal error:  Method foo::__toString() must not throw an exception in /Users/christiankrupa/test/test.php on line 0
>
> Fatal error: Method foo::__toString() must not throw an exception in /Users/christiankrupa/test/test.php on line 0
>
> PHP-Version:
>
> christians-MacBook-Pro:test christiankrupa$ php -v
> PHP 5.5.21 (cli) (built: Jan 24 2015 19:27:09)
> Copyright (c) 1997-2014 The PHP Group
> Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DracoBlue/Craur/issues/26#issuecomment-85119755>.
>


-- 

  http://dracoblue.net

**Comment by Christian-Krupa** [comment]
i would expect an empty string, because i dont know whether the description is empty or not.
```<?php
include "src/Craur.php";
$xml_string = '<?xml version="1.0"?>
<catalog>
   <book_desc id="bk101"></book_desc>
</catalog>';
$craur_node = Craur::createFromXml($xml_string);
echo (string)$craur_node->get('catalog.book_desc');
```

even the default_value failed:

```<?php
include "src/Craur.php";
$xml_string = '<?xml version="1.0"?>
<catalog>
   <book_desc id="bk101"></book_desc>
</catalog>';
$craur_node = Craur::createFromXml($xml_string);
echo (string)$craur_node->get('catalog.book_desc','');
```

**Comment by DracoBlue** [comment]
Already fixed
